// <auto-generated />
using System;
using Backend.Acceso_a_Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeterinariaBackend.Dominio.Atencion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodAtencion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Importe")
                        .HasColumnType("float");

                    b.Property<int?>("Mascotaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Mascotaid");

                    b.ToTable("Atenciones");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Clientes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Mascota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Clientesid")
                        .HasColumnType("int");

                    b.Property<int>("CodigoMascota")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMascota")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clientesid");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Atencion", b =>
                {
                    b.HasOne("VeterinariaBackend.Dominio.Mascota", null)
                        .WithMany("ListaAtencion")
                        .HasForeignKey("Mascotaid");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Mascota", b =>
                {
                    b.HasOne("VeterinariaBackend.Dominio.Clientes", null)
                        .WithMany("ListMascotas")
                        .HasForeignKey("Clientesid");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Clientes", b =>
                {
                    b.Navigation("ListMascotas");
                });

            modelBuilder.Entity("VeterinariaBackend.Dominio.Mascota", b =>
                {
                    b.Navigation("ListaAtencion");
                });
#pragma warning restore 612, 618
        }
    }
}
